build_from:
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.21
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.21
  armv7: ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.21
  armhf: ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.21
  i386: ghcr.io/home-assistant/i386-base-python:3.13-alpine3.21
labels:
  org.opencontainers.image.title: "Codex Code for Home Assistant"
  org.opencontainers.image.description: "Codex/OpenAI-oriented terminal with Home Assistant integration scaffold"
  org.opencontainers.image.source: "https://github.com/robsonfelix/robsonfelix-hass-addons"
  org.opencontainers.image.licenses: "MIT"
